cluster:
  name: devcluster01
  environment: dev
  server: https://kubernetes.default.svc
  project: 1102062e
  gitopsAgentId: devcluster01

# true  -> enable this app for this cluster (even if not in environmentApps)
# false -> disable this app for this cluster (even if environmentApps enables it)
clusterApps:
  hello-world: true